package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"sync"
)

// Crypto core (PSK model, faithful to tinyTouch's design).
//
//   K  = 32-byte pairing key shared by the ESP32 and the Mac
//   n  = 16-byte nonce generated by the ESP32 per request
//
//   reqMAC  = HMAC-SHA256(K, "tsumuji/req/v1" || n)
//   S       = HMAC-SHA256(K, "tsumuji/session/v1" || n)   (session key)
//   ct      = AES-256-CTR(S, iv = n, password)
//   respMAC = HMAC-SHA256(S, "tsumuji/resp/v1" || ct)
//
// The helper rejects a request whose reqMAC does not verify or whose nonce
// has been seen before, and returns no ciphertext in either case.

const (
	PairingKeySize = 32
	NonceSize      = 16
	MACSize        = sha256.Size

	labelRequest  = "tsumuji/req/v1"
	labelSession  = "tsumuji/session/v1"
	labelResponse = "tsumuji/resp/v1"
)

var (
	ErrBadKeySize   = errors.New("pairing key must be 32 bytes")
	ErrBadNonceSize = errors.New("nonce must be 16 bytes")
	ErrBadMAC       = errors.New("request MAC verification failed")
	ErrReplay       = errors.New("nonce replayed")
)

// Zero overwrites b with zeros. Use on every buffer that held secret material.
func Zero(b []byte) {
	for i := range b {
		b[i] = 0
	}
	// Prevent the compiler from eliding the clear.
	subtle.ConstantTimeCompare(b[:0], b[:0])
}

func mac(key []byte, label string, data []byte) []byte {
	h := hmac.New(sha256.New, key)
	h.Write([]byte(label))
	h.Write(data)
	return h.Sum(nil)
}

// RequestMAC computes the MAC the device must attach to an EV request.
func RequestMAC(pairingKey, nonce []byte) []byte {
	return mac(pairingKey, labelRequest, nonce)
}

// VerifyRequestMAC checks the MAC on an EV request in constant time.
func VerifyRequestMAC(pairingKey, nonce, gotMAC []byte) bool {
	if len(pairingKey) != PairingKeySize || len(nonce) != NonceSize {
		return false
	}
	want := RequestMAC(pairingKey, nonce)
	defer Zero(want)
	return hmac.Equal(want, gotMAC)
}

// DeriveSessionKey derives the per-request AES key from the pairing key and nonce.
func DeriveSessionKey(pairingKey, nonce []byte) ([]byte, error) {
	if len(pairingKey) != PairingKeySize {
		return nil, ErrBadKeySize
	}
	if len(nonce) != NonceSize {
		return nil, ErrBadNonceSize
	}
	return mac(pairingKey, labelSession, nonce), nil
}

// aesCTR applies AES-256-CTR with iv over src into a fresh buffer.
func aesCTR(sessionKey, iv, src []byte) ([]byte, error) {
	block, err := aes.NewCipher(sessionKey)
	if err != nil {
		return nil, err
	}
	dst := make([]byte, len(src))
	cipher.NewCTR(block, iv).XORKeyStream(dst, src)
	return dst, nil
}

// EncryptResponse encrypts plaintext under the session key and returns
// (ciphertext, responseMAC). The caller owns plaintext and must Zero it.
func EncryptResponse(sessionKey, nonce, plaintext []byte) (ct, respMAC []byte, err error) {
	if len(sessionKey) != PairingKeySize {
		return nil, nil, ErrBadKeySize
	}
	if len(nonce) != NonceSize {
		return nil, nil, ErrBadNonceSize
	}
	ct, err = aesCTR(sessionKey, nonce, plaintext)
	if err != nil {
		return nil, nil, err
	}
	respMAC = mac(sessionKey, labelResponse, ct)
	return ct, respMAC, nil
}

// DecryptResponse is the device-side counterpart, used by tests to prove
// round-trip compatibility. It verifies respMAC before decrypting.
func DecryptResponse(sessionKey, nonce, ct, respMAC []byte) ([]byte, error) {
	if len(sessionKey) != PairingKeySize {
		return nil, ErrBadKeySize
	}
	if len(nonce) != NonceSize {
		return nil, ErrBadNonceSize
	}
	want := mac(sessionKey, labelResponse, ct)
	defer Zero(want)
	if !hmac.Equal(want, respMAC) {
		return nil, ErrBadMAC
	}
	return aesCTR(sessionKey, nonce, ct)
}

// NewNonce returns a fresh random nonce (device-side helper, used by tests).
func NewNonce() ([]byte, error) {
	n := make([]byte, NonceSize)
	if _, err := rand.Read(n); err != nil {
		return nil, err
	}
	return n, nil
}

// NonceCache remembers recently seen nonces to reject replays.
// It is bounded: once full, the oldest entries are dropped in insertion order.
type NonceCache struct {
	mu    sync.Mutex
	limit int
	seen  map[string]struct{}
	order []string
}

func NewNonceCache(limit int) *NonceCache {
	if limit <= 0 {
		limit = 1024
	}
	return &NonceCache{limit: limit, seen: make(map[string]struct{}, limit)}
}

// Check records nonce and returns ErrReplay if it was already present.
func (c *NonceCache) Check(nonce []byte) error {
	k := string(nonce)
	c.mu.Lock()
	defer c.mu.Unlock()
	if _, dup := c.seen[k]; dup {
		return ErrReplay
	}
	if len(c.order) >= c.limit {
		oldest := c.order[0]
		c.order = c.order[1:]
		delete(c.seen, oldest)
	}
	c.seen[k] = struct{}{}
	c.order = append(c.order, k)
	return nil
}

// ParsePairingKeyHex decodes a 64-hex-char pairing key.
func ParsePairingKeyHex(s string) ([]byte, error) {
	k, err := hex.DecodeString(strings.TrimSpace(s))
	if err != nil {
		return nil, fmt.Errorf("pairing key is not valid hex: %w", err)
	}
	if len(k) != PairingKeySize {
		Zero(k)
		return nil, ErrBadKeySize
	}
	return k, nil
}
